### ISSUE TITLE
Broken mur_compute_stock_loss

### ISSUE THREAD

**Issue by RenaudWasTaken** [Dubrzr/thjx2017#5]
The function `mur_compute_stock_loss` which was implemented in the following commit 9c6838671b3f8626361aaa4509e86ee1b4771839  is completly broken

This function's current implementation behavior is to call itself indefinitely.

**Comment by tgy** [comment]
I have created PR https://github.com/Dubrzr/thjx2017/pull/6 that probably solves the problem.
